// Generated by Wrangler by running `wrangler types`

export {};
declare global {
	const SOURCE_TIMESTAMPS: KVNamespace;
	const WEBHOOK_URL: string;
	const HS_API_URL: string;
	const SS_WWW_URL: string;
}
