#:schema node_modules/wrangler/config-schema.json
name = "fingerpori-webhook"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 4 * * *"]